<?php
/**
 * @file
 * Module file for security audit
 *
 * This module purposely contains unsafe code for educational purposes.
 * Never use this module on a production site!
 */

/**
 * Implements hook_menu().
 *
 */
function security_audit_menu() {
  $items['security_audit/bad/welcome/%'] = array(
    'title' => 'Welcome',
    'page callback' => 'security_audit_welcome_callback_bad',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['security_audit/good/welcome/%'] = array(
    'title' => 'Welcome',
    'page callback' => 'security_audit_welcome_callback_good',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['security_audit/bad/node/%'] = array(
    'title' => 'Display a node',
    'page callback' => 'security_audit_node_callback_bad',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['security_audit/good/node/%'] = array(
    'title' => 'Display a node',
    'page callback' => 'security_audit_node_callback_good',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['security_audit/bad/form'] = array(
    'title' => 'Display a form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('security_audit_form_bad'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['security_audit/good/form'] = array(
    'title' => 'Display a form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('security_audit_form_bad'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['security_audit/bad/disable'] = array(
    'title' => 'Unpublish any content',
    'access arguments' => array('edit any article content'),
    'page callback' => 'security_audit_node_unpublish_bad',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
  );

  $items['security_audit/good/disable'] = array(
    'title' => 'Unpublish any content',
    'access arguments' => array('edit any article content'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('security_audit_node_unpublish_good'),
    'type' => MENU_CALLBACK,
  );

  $items['security_audit/bad/node_list'] = array(
    'title' => 'List of nodes',
    'page callback' => 'security_audit_node_list_bad',
    'access arguments' => array('access content'),
  );

  return $items;
  
}

/**
 * Callback which displays simple hello message
 * @param $name
 * @return string
 */
function security_audit_welcome_callback_bad($name) {
  // Security problem: user input is not being sanitised and passed directly to the browser.
  $output = 'Hello ' . $name;

  return $output;
}

/**
 * Callback which displays simple hello message
 * @param $name
 * @return string
 */
function security_audit_welcome_callback_good($name) {
  // use t() and pass variable via placeholder with @ prefix to check_plain.
  $output = t('Hello @name', array('@name' => $name));

  return $output;
}

/**
 * Callback which displays a node
 */
function security_audit_node_callback_bad($nid) {

  // Example if SQL Injection. User can pass in another SQL query to alter the query below.
  $nid = $_GET['nid'];
  $title = db_query("SELECT title FROM node where nid = $nid")->fetchField();

  return $title;
}

/**
 * Callback which displays a node
 */
function security_audit_node_callback_good($nid) {

  // Pass variable to query via placeholder to prevent SQL Injection.
  $nid = $_GET['nid'];
  $title = db_query("SELECT title FROM node where nid = :nid", array(':nid' => $nid))->fetchField();

  return $title;
}



/**
 * Implements hook_form().
 *
 */
function security_audit_form_bad($form, &$form_state) {

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => 'title',
    '#required' => TRUE, '#weight' => -5
  );


  $form['buttons']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;

}

/**
 * Submit handler for security_audit_form.
 * @param $form
 * @param $form_state
 */
function security_audit_form_bad_submit($form, &$form_state) {
  // $form_state['input'] is raw user submitted data that has not been sanitised. Use $form_state['values'] instead
  drupal_set_message('You have submitted data with the following title ' . $form_state['input']['title']);
}

/**
 * Implements hook_form().
 *
 */
function security_audit_form_good($form, &$form_state) {

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => 'title',
    '#required' => TRUE,
  );


  $form['buttons']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;

}

/**
 * Submit handler for security_audit_form.
 * @param $form
 * @param $form_state
 */
function security_audit_form_good_submit($form, &$form_state) {
  // Uses $form_state['values']
  drupal_set_message('You have submitted data with the following title ' . $form_state['values']['title']);
}

/**
 * Callback to unpublish a node.
 * @param $nid
 * @return null|string
 */
function security_audit_node_unpublish_bad($nid) {
  // This is a CSRF and SQL Injection vulnerability.
  // A user can add an image with src being the path to access this callback. Another user with the correct permissions could execute it.
  db_query("UPDATE {node} SET status = 0 WHERE nid = $nid");
  drupal_set_message('Unpublished node with nid: ' . $nid);
  return t('Node unpublished');
}

/**
 * Form to unpublish a node.
 * @param $nid
 * @return null|string
 */
function security_audit_node_unpublish_good($form, &$form_state) {

  $nodes = node_load_multiple(array(), array('type' => 'article'));

  $options = array();
  foreach($nodes as $node) {
    $options[$node->nid] = $node->title;
  }

  $form['node'] = array(
    '#type' => 'select',
    '#options' => $options,
    '#title' => 'Node to unpublish',
    '#required' => TRUE,
  );

  $form['buttons']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

/*
 * Submit handler for security_audit_node_unpublish_good.
 */
function security_audit_node_unpublish_good_submit($form, &$form_state) {
  db_query("UPDATE {node} SET status = 0 WHERE nid = :nid", array(':nid' => $form_state['values']['node']));
  drupal_set_message(t('Node unpublished'));
}

/**
 * Callback to display nodes list.
 */
function security_audit_node_list_bad() {
  $query = db_select('node', 'n');
  $query->fields('n', array('nid', 'title'));
  $result = $query->execute();

  $item_link = array();
  foreach ($result as $row) {
    $item_link[] = l(check_plain($row->title), 'node/' . $row->nid);
  }

  $output = theme('item_list', array('items' => $item_link));

  return $output;

}